# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ray-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 2Gi
