{{- if .Values.headService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headService.name | quote }}
spec:
  type: {{ .Values.headService.type }}
  selector:
    ray.io/cluster: {{ .Values.rayCluster.name | quote }}
  ports:
{{- range .Values.headService.ports }}
  - name: {{ .name | quote }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
{{- if .nodePort }}
    nodePort: {{ .nodePort }}
{{- end }}
{{- end }}
{{- end }}
