{{- if .Values.nfs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.nfs.pv.name | quote }}
spec:
  capacity:
    storage: {{ .Values.nfs.pv.capacity | quote }}
  volumeMode: Filesystem
  accessModes:
{{- range .Values.nfs.pv.accessModes }}
  - {{ . | quote }}
{{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.nfs.storageClass.reclaimPolicy | quote }}
  storageClassName: {{ .Values.nfs.storageClass.name | quote }}
  mountOptions:
{{- range .Values.nfs.pv.mountOptions }}
  - {{ . | quote }}
{{- end }}
  nfs:
    server: {{ .Values.nfs.pv.nfs.server | quote }}
    path: {{ .Values.nfs.pv.nfs.path | quote }}
{{- end }}
