apiVersion: {{ .Values.rayCluster.apiVersion }}
kind: RayCluster
metadata:
  name: {{ .Values.rayCluster.name | quote }}
spec:
  enableInTreeAutoscaling: {{ .Values.rayCluster.enableInTreeAutoscaling }}
  rayVersion: {{ .Values.rayCluster.rayVersion | quote }}
  headGroupSpec:
    rayStartParams:
{{- toYaml .Values.rayCluster.head.rayStartParams | nindent 6 }}
    template:
      spec:
{{- if .Values.rayCluster.head.initSharedStorage.enabled }}
        initContainers:
        - name: init-shared-storage
          image: {{ .Values.rayCluster.head.initSharedStorage.image | quote }}
          securityContext:
            runAsUser: {{ .Values.rayCluster.head.initSharedStorage.runAsUser }}
          command:
{{- toYaml .Values.rayCluster.head.initSharedStorage.command | nindent 10 }}
          args:
          - {{ .Values.rayCluster.head.initSharedStorage.args | quote }}
          volumeMounts:
          - name: shared-data
            mountPath: {{ .Values.rayCluster.sharedMountPath | quote }}
{{- end }}
        containers:
        - name: ray-head
          image: {{ .Values.rayCluster.head.image | quote }}
          ports:
{{- toYaml .Values.rayCluster.head.ports | nindent 10 }}
          volumeMounts:
          - name: shared-data
            mountPath: {{ .Values.rayCluster.sharedMountPath | quote }}
          resources:
{{- toYaml .Values.rayCluster.head.resources | nindent 12 }}
        volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Values.sharedPvc.name | quote }}
  workerGroupSpecs:
{{- if .Values.rayCluster.workers.cpuGroup.enabled }}
  - groupName: {{ .Values.rayCluster.workers.cpuGroup.groupName | quote }}
    minReplicas: {{ .Values.rayCluster.workers.cpuGroup.minReplicas }}
    maxReplicas: {{ .Values.rayCluster.workers.cpuGroup.maxReplicas }}
    replicas: {{ .Values.rayCluster.workers.cpuGroup.replicas }}
    rayStartParams:
{{- toYaml .Values.rayCluster.workers.cpuGroup.rayStartParams | nindent 6 }}
    template:
      spec:
        containers:
        - name: {{ .Values.rayCluster.workers.cpuGroup.name | quote }}
          image: {{ .Values.rayCluster.workers.cpuGroup.image | quote }}
          volumeMounts:
          - name: shared-data
            mountPath: {{ .Values.rayCluster.sharedMountPath | quote }}
          resources:
{{- toYaml .Values.rayCluster.workers.cpuGroup.resources | nindent 12 }}
        volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Values.sharedPvc.name | quote }}
{{- end }}
{{- if .Values.rayCluster.workers.gpuGroup.enabled }}
  - groupName: {{ .Values.rayCluster.workers.gpuGroup.groupName | quote }}
    minReplicas: {{ .Values.rayCluster.workers.gpuGroup.minReplicas }}
    maxReplicas: {{ .Values.rayCluster.workers.gpuGroup.maxReplicas }}
    replicas: {{ .Values.rayCluster.workers.gpuGroup.replicas }}
    rayStartParams:
{{- toYaml .Values.rayCluster.workers.gpuGroup.rayStartParams | nindent 6 }}
    template:
      spec:
        containers:
        - name: {{ .Values.rayCluster.workers.gpuGroup.name | quote }}
          image: {{ .Values.rayCluster.workers.gpuGroup.image | quote }}
          volumeMounts:
          - name: shared-data
            mountPath: {{ .Values.rayCluster.sharedMountPath | quote }}
          resources:
{{- toYaml .Values.rayCluster.workers.gpuGroup.resources | nindent 12 }}
        volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Values.sharedPvc.name | quote }}
{{- if .Values.rayCluster.workers.gpuGroup.runtimeClassName }}
        runtimeClassName: {{ .Values.rayCluster.workers.gpuGroup.runtimeClassName | quote }}
{{- end }}
{{- end }}
