{{- if .Values.sharedPvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sharedPvc.name | quote }}
spec:
  accessModes:
{{- range .Values.sharedPvc.accessModes }}
  - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.sharedPvc.size | quote }}
  storageClassName: {{ .Values.sharedPvc.storageClassName | quote }}
  volumeName: {{ .Values.sharedPvc.volumeName | quote }}
{{- end }}
