apiVersion: v1
kind: PersistentVolume
metadata:
  name: ray-shared-nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-direct
  nfs:
    server: {{ .Values.nfs.clusterIP }}
    path: {{ .Values.nfs.exportPathClient }}

