{{- if .Values.rayCluster.enabled }}
{{- $clusterName := ( .Values.rayCluster.nameOverride | default (include "ray-nfs-chart.fullname" .) ) }}
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: {{ $clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  rayVersion: {{ .Values.rayCluster.rayVersion | quote }}

  headGroupSpec:
    serviceType: {{ .Values.rayCluster.head.serviceType }}
    template:
      spec:
        # Ensures the pod explicitly runs as the Ray user
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
        
        # This container fixes permissions before Ray starts
        # In ray-cluster.yaml
        initContainers:
          - name: volume-mount-permissions
            image: busybox:latest
            # Dynamically inject the mountPath from values.yaml
            command: ["sh", "-c", "chown -R 1000:1000 {{ .Values.rayCluster.sharedStorage.mountPath }} && chmod 775 {{ .Values.rayCluster.sharedStorage.mountPath }}"]
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: shared-storage
                mountPath: {{ .Values.rayCluster.sharedStorage.mountPath }}

        containers:
          - name: ray-head
            image: {{ .Values.rayCluster.image }}
            volumeMounts:
              - name: shared-storage
                mountPath: {{ .Values.rayCluster.sharedStorage.mountPath }}
        volumes:
          - name: shared-storage
            persistentVolumeClaim:
              claimName: {{ .Values.sharedPvc.name }}

  workerGroupSpecs:
    - groupName: worker-group
      replicas: {{ .Values.rayCluster.worker.replicas }}
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          
          initContainers:
            - name: volume-mount-permissions
              image: busybox:latest
              # Dynamically inject the mountPath from values.yaml
              command: ["sh", "-c", "chown -R 1000:1000 {{ .Values.rayCluster.sharedStorage.mountPath }} && chmod 775 {{ .Values.rayCluster.sharedStorage.mountPath }}"]
              securityContext:
                runAsUser: 0
              volumeMounts:
                - name: shared-storage
                  mountPath: {{ .Values.rayCluster.sharedStorage.mountPath }}

          containers:
            - name: ray-worker
              image: {{ .Values.rayCluster.image }}
              volumeMounts:
                - name: shared-storage
                  mountPath: {{ .Values.rayCluster.sharedStorage.mountPath }}
          volumes:
            - name: shared-storage
              persistentVolumeClaim:
                claimName: {{ .Values.sharedPvc.name }}
{{- end }}