apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vscode-ray.fullname" . }}
  labels:
{{ include "vscode-ray.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "vscode-ray.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{ include "vscode-ray.selectorLabels" . | nindent 8 }}
{{- with .Values.podLabels }}
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | nindent 8 }}
{{- end }}
    spec:
      securityContext:
{{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: code-server
          image: "{{ .Values.workspace.image.repository }}:{{ .Values.workspace.image.tag }}"
          imagePullPolicy: {{ .Values.workspace.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.workspace.port }}
              protocol: TCP
          env:
            - name: {{ .Values.ray.addressEnvName }}
              value: {{ printf "ray://%s:10001" (include "vscode-ray.rayHeadServiceName" .) | quote }}
            - name: {{ .Values.ray.sharedStoragePathEnvName }}
              value: {{ .Values.ray.sharedStoragePathValue | quote }}
            - name: WORKSPACE_PVC_NAME
              value: {{ include "vscode-ray.pvcName" . | quote }}
{{- with .Values.env }}
{{ toYaml . | nindent 12 }}
{{- end }}
          securityContext:
{{ toYaml .Values.securityContext | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: shared-storage
              mountPath: {{ .Values.sharedStorage.mountPath | quote }}
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: {{ include "vscode-ray.pvcName" . | quote }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
