apiVersion: v1
kind: Service
metadata:
  name: {{ include "vscode-ray.fullname" . }}
  labels:
{{ include "vscode-ray.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "vscode-ray.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
